### ISSUE TITLE
New version of Vue or vue-template-loader introduces the _vm._ssrNode function

### ISSUE THREAD

**Issue by Riduidel** [eddyerburgh/avoriaz#123]
I've recently upgraded my Vue install from 2.3.4 to 2.4.2
Since then, I have a unit test which outputs the following warning

	(found in <Root>)
	TypeError: _vm._ssrNode is not a function
		at Proxy.eval (eval at patchTemplate (myWorkspace\test\Unit\avoriazNode.js:35:10), <anonymous>:62:51)
		at VueComponent.Vue._render (myWorkspace\node_modules\vue\dist\vue.runtime.common.js:4126:22)
		at VueComponent.updateComponent (myWorkspace\node_modules\vue\dist\vue.runtime.common.js:2536:21)
		at Watcher.get (myWorkspace\node_modules\vue\dist\vue.runtime.common.js:2879:25)
		at new Watcher (myWorkspace\node_modules\vue\dist\vue.runtime.common.js:2868:12)
		at mountComponent (myWorkspace\node_modules\vue\dist\vue.runtime.common.js:2540:17)
		at VueComponent.Vue$3.$mount (myWorkspace\node_modules\vue\dist\vue.runtime.common.js:7399:10)
		at mount (myWorkspace\node_modules\avoriaz\dist\avoriaz.js:761:8)
		at Object.shallow (myWorkspace\node_modules\avoriaz\dist\avoriaz.js:840:10)
		at shallow (myWorkspace\test\Unit\avoriazNode.js:74:18)
		at Context._callee$ (myWorkspace\test\Unit\components\Welcome\WelcomeHub.spec.js:22:21)
		at tryCatch (myWorkspace\node_modules\regenerator-runtime\runtime.js:65:40)
		at Generator.invoke [as _invoke] (myWorkspace\node_modules\regenerator-runtime\runtime.js:303:22)
		at Generator.prototype.(anonymous function) [as next] (myWorkspace\node_modules\regenerator-runtime\runtime.js:117:21)
		at step (myWorkspace\.tmp\mocha-webpack\15fc5b728c8fba473e537cc06e31fd7e\15fc5b728c8fba473e537cc06e31fd7e-output.js:3421:191)
		at myWorkspace\.tmp\mocha-webpack\15fc5b728c8fba473e537cc06e31fd7e\15fc5b728c8fba473e537cc06e31fd7e-output.js:3421:437
		at Promise (<anonymous>)
		at Context.<anonymous> (myWorkspace\.tmp\mocha-webpack\15fc5b728c8fba473e537cc06e31fd7e\15fc5b728c8fba473e537cc06e31fd7e-output.js:3421:99)
		at callFn (myWorkspace\node_modules\mocha\lib\runnable.js:348:21)
		at Test.Runnable.run (myWorkspace\node_modules\mocha\lib\runnable.js:340:7)
		at Runner.runTest (myWorkspace\node_modules\mocha\lib\runner.js:443:10)
		at myWorkspace\node_modules\mocha\lib\runner.js:549:12
		at next (myWorkspace\node_modules\mocha\lib\runner.js:361:14)
		at myWorkspace\node_modules\mocha\lib\runner.js:371:7
		at next (myWorkspace\node_modules\mocha\lib\runner.js:295:14)
		at Immediate.<anonymous> (myWorkspace\node_modules\mocha\lib\runner.js:339:5)
		at runCallback (timers.js:800:20)
		at tryOnImmediate (timers.js:762:5)
		at processImmediate [as _immediateCallback] (timers.js:733:5)
		√ should replace url with / on completed

According to a rapid search, the `_ssrNode` is declared in `vue\src\server\optimizing-compiler\runtime-helpers.js` the following way

	export function installSSRHelpers (vm: Component) {
	  if (vm._ssrNode) return
	  let Ctor = vm.constructor
	  while (Ctor.super) {
		Ctor = Ctor.super
	  }
	  Object.assign(Ctor.prototype, {
		_ssrEscape: escape,
		_ssrNode: renderStringNode,
		_ssrList: renderStringList,
		_ssrAttr: renderAttr,
		_ssrAttrs: renderAttrs,
		_ssrDOMProps: renderDOMProps,
		_ssrClass: renderSSRClass,
		_ssrStyle: renderSSRStyle
	  })
	}

Hope this will help ....

**Comment by eddyerburgh** [comment]
Are you setting `target: node` in a WebPack config? Removing this option will solve this error. 

If you aren't, can you post a minimal reproducible example?

**Comment by Riduidel** [comment]
Indeed, removing the `target: node` removed the error.

Thanks !

**Comment by RachnaKinger11** [comment]
I am getting a similar error but is for **_vm._ssrList is not a function**

TypeError: _vm._ssrList is not a function
    at Proxy.render (/frontEnd/lg-component-breadcrumbs/dist/webpack:/components/Breadcrumbs.vue:8:1)
    at VueComponent.Vue._render (/frontEnd/lg-component-breadcrumbs/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4540:1)
    at VueComponent.updateComponent (/frontEnd/lg-component-breadcrumbs/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2784:1)

 _ssrList is declared in vue\src\server\optimizing-compiler\runtime-helpers.js

```
/* @flow */

import { escape, isSSRUnsafeAttr } from 'web/server/util'
import { isObject, extend } from 'shared/util'
import { renderAttr } from 'web/server/modules/attrs'
import { renderClass } from 'web/util/class'
import { genStyle } from 'web/server/modules/style'
import { normalizeStyleBinding } from 'web/util/style'

import {
  normalizeChildren,
  simpleNormalizeChildren
} from 'core/vdom/helpers/normalize-children'

import {
  propsToAttrMap,
  isRenderableAttr
} from 'web/server/util'

const ssrHelpers = {
  _ssrEscape: escape,
  _ssrNode: renderStringNode,
  _ssrList: renderStringList,
  _ssrAttr: renderAttr,
  _ssrAttrs: renderAttrs,
  _ssrDOMProps: renderDOMProps,
  _ssrClass: renderSSRClass,
  _ssrStyle: renderSSRStyle
}
```

Don't have target:node in config though
