### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by TheDutchCoder** [eddyerburgh/avoriaz#89]
Hiya,

Was just trying to install avoriaz and give it a test, but it throws an error on the latest release:

Node 4.8.2
npm 5

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/node',
1 verbose cli   '/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'avoriaz' ]
2 info using npm@5.0.0
3 info using node@v4.8.2
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 200 https://registry.npmjs.org/avoriaz 20ms (from cache)
7 silly pacote tag manifest for avoriaz@latest fetched in 51ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 verbose stack SyntaxError: Unexpected token <
11 verbose stack     at Object.parse (native)
11 verbose stack     at module.exports (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/lib/utils/parse-json.js:3:15)
11 verbose stack     at /Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/lib/install/read-shrinkwrap.js:31:20
11 verbose stack     at tryCatcher (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Holder$3._callFunction (eval at <anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:1:0), <anonymous>:14:44)
11 verbose stack     at Holder$3.checkFulfillment (eval at <anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:1:0), <anonymous>:29:30)
11 verbose stack     at Promise.eval (eval at <anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:1:0), <anonymous>:6:20)
11 verbose stack     at Promise._settlePromise (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
11 verbose stack     at Promise._settlePromise0 (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Promise._fulfill (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
11 verbose stack     at Promise._settlePromise (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
11 verbose stack     at Promise._settlePromise0 (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Promise._fulfill (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
11 verbose stack     at /Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
12 verbose cwd /Users/reinierkaper/projects/docker/canvaspop
13 verbose Darwin 16.6.0
14 verbose argv "/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/node" "/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/npm" "install" "--save-dev" "avoriaz"
15 verbose node v4.8.2
16 verbose npm  v5.0.0
17 error Unexpected token <
18 verbose exit [ 1, true ]

```

**Comment by eddyerburgh** [comment]
Looks like a problem with npm - https://github.com/npm/npm/issues/17492

**Comment by eddyerburgh** [comment]
Did you manage to solve this?

**Comment by TheDutchCoder** [comment]
So it turns out that it works on a clean install, with only Vue installed, but not in our current project (which has hundreds of other deps installed).

It seems to die on `loadIdealTree:loadAllDepsIntoIdealTree`

**Comment by eddyerburgh** [comment]
Did you try deleting the npm cache? It might solve your issue.

On OSX/ linux - 

```
rm -rf ~/.npm
```

I know that npm 5 has a few bugs related to their new cacheing implementation.

**Comment by TheDutchCoder** [comment]
No difference unfortunately :(

Not sure what else to do. It installs fine in a clean environment, so I don't know if it's an issue with your package or another one.

**Comment by eddyerburgh** [comment]
I think it's an issue with npm, especially if the problem is coming from `loadIdealTree:loadAllDepsIntoIdealTree`

**Comment by TheDutchCoder** [comment]
Yeah that makes sense. I'll close this issue for now and see if I can get it to work in some other way. Thanks!
